<?php

declare(strict_types=1);

/**
 * Bimoo — Moodle Stub Generator
 *
 * @author     Michael Meneses <michael@middag.com.br>
 * @copyright  2026 MIDDAG (https://www.middag.com.br)
 * @license    GNU General Public License v3.0 or later
 */

namespace Bimoo\Stub\NodeVisitor;

class GlobalVarCollector
{
    /**
     * @param array<string, string> $typeMap Variable name => type (e.g., '$DB' => '\\moodle_database')
     */
    public function __construct(
        private readonly array $typeMap,
    ) {
    }

    /**
     * Generate the globals.stub.php content.
     */
    public function generate(): string
    {
        $lines = [
            '<?php',
            '',
            '/**',
            ' * Auto-generated stub file for Moodle global variables.',
            ' *',
            ' * @generated by bimoo — https://github.com/michaelmeneses/bimoo',
            ' * @link https://github.com/michaelmeneses/moodle-stubs',
            ' */',
            '',
        ];

        foreach ($this->typeMap as $varName => $type) {
            $cleanName = ltrim($varName, '$');
            $lines[] = "/** @var {$type} \${$cleanName} */";
            $lines[] = "global \${$cleanName};";
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    public function getCount(): int
    {
        return count($this->typeMap);
    }
}
