<?php

declare(strict_types=1);

/**
 * Bimoo — Moodle Stub Generator
 *
 * @author     Michael Meneses <michael@middag.com.br>
 * @copyright  2026 MIDDAG (https://www.middag.com.br)
 * @license    GNU General Public License v3.0 or later
 */

namespace Bimoo\Tests\Stub\NodeVisitor;

use Bimoo\Stub\NodeVisitor\GlobalVarCollector;
use PHPUnit\Framework\TestCase;

class GlobalVarCollectorTest extends TestCase
{
    public function testGeneratesGlobalsStubContent(): void
    {
        $typeMap = [
            '$DB' => '\\moodle_database',
            '$CFG' => '\\stdClass',
        ];

        $collector = new GlobalVarCollector($typeMap);
        $content = $collector->generate();

        $this->assertStringContainsString('/** @var \\moodle_database $DB */', $content);
        $this->assertStringContainsString('global $DB;', $content);
        $this->assertStringContainsString('/** @var \\stdClass $CFG */', $content);
        $this->assertStringContainsString('global $CFG;', $content);
    }

    public function testGeneratesValidPhpWithHeader(): void
    {
        $typeMap = ['$DB' => '\\moodle_database'];

        $collector = new GlobalVarCollector($typeMap);
        $content = $collector->generate();

        $this->assertStringStartsWith('<?php', $content);
        $this->assertStringContainsString('@generated by bimoo', $content);
    }

    public function testLoadsTypeMapFromConfigFile(): void
    {
        $configPath = __DIR__ . '/../../../config/global-vars.php';

        if (!file_exists($configPath)) {
            $this->markTestSkipped('config/global-vars.php not found');
        }

        $typeMap = require $configPath;
        $collector = new GlobalVarCollector($typeMap);
        $content = $collector->generate();

        $this->assertStringContainsString('global $DB;', $content);
        $this->assertStringContainsString('global $PAGE;', $content);
        $this->assertStringContainsString('global $OUTPUT;', $content);
    }

    public function testGetCount(): void
    {
        $typeMap = [
            '$DB' => '\\moodle_database',
            '$CFG' => '\\stdClass',
            '$ME' => 'string',
        ];

        $collector = new GlobalVarCollector($typeMap);

        $this->assertSame(3, $collector->getCount());
    }
}
