<?php

declare(strict_types=1);

/**
 * Bimoo — Moodle Stub Generator
 *
 * @author     Michael Meneses <michael@middag.com.br>
 * @copyright  2026 MIDDAG (https://www.middag.com.br)
 * @license    GNU General Public License v3.0 or later
 */

namespace Bimoo\Tests\Stub\Writer;

use Bimoo\Stub\Writer\StubFileWriter;
use PhpParser\ParserFactory;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Filesystem\Filesystem;

class StubFileWriterTest extends TestCase
{
    private string $outputDir;
    private Filesystem $fs;
    private StubFileWriter $writer;

    protected function setUp(): void
    {
        $this->fs = new Filesystem();
        $this->outputDir = sys_get_temp_dir() . '/bimoo_writer_test_' . uniqid();
        $this->fs->mkdir($this->outputDir);
        $this->writer = new StubFileWriter($this->outputDir);
    }

    protected function tearDown(): void
    {
        $this->fs->remove($this->outputDir);
    }

    private function parseCode(string $code): array
    {
        $parser = (new ParserFactory())->createForNewestSupportedVersion();

        return $parser->parse($code);
    }

    public function testWritesStubFileWithCorrectPath(): void
    {
        $stmts = $this->parseCode('<?php function hello(): void {}');
        $this->writer->write($stmts, 'lib/moodlelib.php');

        $expectedPath = $this->outputDir . '/lib/moodlelib.stub.php';
        $this->assertFileExists($expectedPath);
    }

    public function testStubFileContainsHeader(): void
    {
        $stmts = $this->parseCode('<?php function hello(): void {}');
        $this->writer->write($stmts, 'lib/moodlelib.php');

        $content = file_get_contents($this->outputDir . '/lib/moodlelib.stub.php');

        $this->assertStringContainsString('@generated by bimoo', $content);
        $this->assertStringContainsString('lib/moodlelib.php', $content);
    }

    public function testStubFileContainsCode(): void
    {
        $stmts = $this->parseCode('<?php function hello(): void {}');
        $this->writer->write($stmts, 'lib/moodlelib.php');

        $content = file_get_contents($this->outputDir . '/lib/moodlelib.stub.php');

        $this->assertStringContainsString('function hello(): void', $content);
    }

    public function testCreatesNestedDirectories(): void
    {
        $stmts = $this->parseCode('<?php class DB {}');
        $this->writer->write($stmts, 'lib/dml/moodle_database.php');

        $this->assertFileExists($this->outputDir . '/lib/dml/moodle_database.stub.php');
    }

    public function testWriteGlobalsFile(): void
    {
        $content = "<?php\n/** @var \\moodle_database \$DB */\nglobal \$DB;\n";
        $this->writer->writeRaw($content, 'globals.stub.php');

        $this->assertFileExists($this->outputDir . '/globals.stub.php');
        $this->assertStringContainsString('global $DB', file_get_contents($this->outputDir . '/globals.stub.php'));
    }

    public function testHasDeclarationsReturnsTrueForClass(): void
    {
        $stmts = $this->parseCode('<?php class Foo {}');
        $this->assertTrue($this->writer->hasDeclarations($stmts));
    }

    public function testHasDeclarationsReturnsFalseForEmpty(): void
    {
        $this->assertFalse($this->writer->hasDeclarations([]));
    }
}
