<?php

declare(strict_types=1);

/**
 * Bimoo — Moodle Stub Generator
 *
 * @author     Michael Meneses <michael@middag.com.br>
 * @copyright  2026 MIDDAG (https://www.middag.com.br)
 * @license    GNU General Public License v3.0 or later
 */

namespace Bimoo\Stub\Writer;

use PhpParser\Node\Stmt;
use PhpParser\PrettyPrinter\Standard as PrettyPrinter;
use Symfony\Component\Filesystem\Filesystem;

class StubFileWriter
{
    private PrettyPrinter $printer;
    private Filesystem $filesystem;

    public function __construct(
        private readonly string $outputDir,
    ) {
        $this->printer = new PrettyPrinter();
        $this->filesystem = new Filesystem();
    }

    /**
     * Write a stub file from AST statements.
     *
     * @param Stmt[] $stmts The cleaned AST statements
     * @param string $relativePath Original file path relative to Moodle root (e.g., 'lib/moodlelib.php')
     */
    public function write(array $stmts, string $relativePath): void
    {
        $stubPath = $this->getStubPath($relativePath);
        $header = $this->generateHeader($relativePath);
        $code = $this->printer->prettyPrintFile($stmts);

        // Replace the opening <?php tag with our header
        $content = preg_replace('/^<\?php\s*/', '', $code) ?? $code;
        $content = $header . "\n" . $content;

        $this->filesystem->mkdir(dirname($stubPath));
        $this->filesystem->dumpFile($stubPath, $content);
    }

    /**
     * Write raw content to a file (used for globals.stub.php).
     */
    public function writeRaw(string $content, string $filename): void
    {
        $path = $this->outputDir . '/' . $filename;
        $this->filesystem->mkdir(dirname($path));
        $this->filesystem->dumpFile($path, $content);
    }

    /**
     * Check whether the AST contains any meaningful declarations.
     *
     * @param Stmt[] $stmts
     */
    public function hasDeclarations(array $stmts): bool
    {
        foreach ($stmts as $stmt) {
            if ($stmt instanceof Stmt\Class_
                || $stmt instanceof Stmt\Interface_
                || $stmt instanceof Stmt\Trait_
                || $stmt instanceof Stmt\Enum_
                || $stmt instanceof Stmt\Function_
                || $stmt instanceof Stmt\Const_
                || $stmt instanceof Stmt\Expression
            ) {
                return true;
            }

            if ($stmt instanceof Stmt\Namespace_ && $this->hasDeclarations($stmt->stmts)) {
                return true;
            }
        }

        return false;
    }

    private function getStubPath(string $relativePath): string
    {
        $stubRelative = preg_replace('/\.php$/', '.stub.php', $relativePath);

        return $this->outputDir . '/' . $stubRelative;
    }

    private function generateHeader(string $relativePath): string
    {
        return <<<HEADER
            <?php

            /**
             * Auto-generated stub file for Moodle's {$relativePath}
             *
             * @generated by bimoo — https://github.com/michaelmeneses/bimoo
             * @link https://github.com/michaelmeneses/moodle-stubs
             */
            HEADER;
    }
}
